### ISSUE TITLE
Unable to locate from Hubzilla

### ISSUE THREAD

**Issue by sunjam** [jdormit/pterotype#12]
Mastodon is able to find them, but I'm unable to locate my federated activity stream or blog@james.network from within [Hubzilla](https://project.hubzilla.org/page/hubzilla/hubzilla-project).

**Comment by sunjam** [comment]
_Follow up from Hubzilla dev:_ 


The details are that we weren't recognising "Organization" as a valid actor type.

[master 37a77cc] support pterotype

We'll see if this can be pushed into the next point release.

**Comment by jdormit** [comment]
Great news! I'm going to close this in that case since it sounds like the problem wasn't on our end. Thanks for following up!
