### ISSUE TITLE
Federation with Mastodon is broken?

### ISSUE THREAD

**Issue by jdormit** [jdormit/pterotype#5]
I can't tell if this is an issue with Mastodon or Pterotype.

I deleted and re-created the QA instance. Now, when I search for it in the Mastodon search bar, both on mastodon.technology and a locally running instance, no results come up. From the local Mastodon server logs I can see that the webfinger request is made and receives a 200 back from Pterotype, and I've confirmed manually that the webfinger endpoint and the blog actor endpoint are both working.

So what's going on here? Is Mastodon doing some sort of weird caching thing?

**Comment by jdormit** [comment]
So I created an account on a new Mastodon instance, mastodon.social, which had never seen the QA instance actor before, and repeated the search. That instance found the QA actor with no problem. So it does seem to be a weird caching issue.

That also revealed an unrelated issue - when I try to follow the QA instance with my new mastodon.social account, I'm getting a 404 not found. Without having access to the server logs it's hard to say what that actually means, so I'll try to reproduce elsewhere.

**Comment by jdormit** [comment]
Update: mastodon.social actually just had a cached version of the blog actor (with out-of-date info). So basically it seems like the problem is that Mastodon aggressively caches everything and if you delete stuff it doesn't like to evict the cache.

**Comment by jdormit** [comment]
So I made a new QA instance with a different URL, and webfinger discovery and follows are working fine with the new blog. However, federation doesn't seem to be working - investigating why now.

**Comment by DeadSuperHero** [comment]
Thanks for the updates!

**Comment by jdormit** [comment]
The error I'm getting back from Mastodon when we attempt to deliver the activity is:

`Public key not found for key http://qa1.getpterotype.com/wp-json/pterotype/v1/actor/-blog#publicKey`.

So I think maybe the public key field is still getting compacted (reduced to just an ID), which doesn't actually resolve if you make a request for it. So there are at least two things to resolve here: 

1. Make the public key fields have a real URL for their IDs
2. Make sure Mastodon gets a hydrated copy of the public key

**Comment by jdormit** [comment]
Ha, figured it out. The problem was that I was serving the WordPress instance over `https`, but it had its site URL configured to `http://qa1.getpterotype.com` (not `https`). This meant that the actor's `url` was mismatched between Mastodon and Pterotype, so Mastodon couldn't find the actor when it received an update. Once I updated the WordPress site URL (in settings) to `https://qa1.getpterotype.com`, the federation worked just fine.

This means that the WebFinger discovery problem mentioned in the first issue comment is almost certainly a caching problem on Mastodon's side. I'm going to close this issue out, since it's not a problem with Pterotype, and think more about what to do about Mastodon's aggressive caching.

**Comment by jdormit** [comment]
Also, to close the loop on this, I re-did a search for the original QA instance (the one that was deleted and re-created), and it succeeded with no problem. So the cache does get evicted periodically.
