### ISSUE TITLE
[Feature Request] Show fedi avatars on comments

### ISSUE THREAD

**Issue by DeadSuperHero** [jdormit/pterotype#6]
At the moment, responses from fediverse clients show up as comments on Wordpress articles. This is a good start, but presently these comments do not render the avatars.

![will_this_post_get_published__ _we_distribute](https://user-images.githubusercontent.com/401560/48282721-4f3f7000-e40f-11e8-8df0-cef59b56b931.png)

A visual gimmick I'm trying to accomplish with my Wordpress is to make comments look like statuses from a fediverse client. Presently that's a little hard to do without avatars!

**Comment by jdormit** [comment]
For sure, this wouldn't be very hard to do. Putting it on the roadmap.

**Comment by jdormit** [comment]
Okay, this is released in 1.2.8:
![avatar-fedi](https://user-images.githubusercontent.com/6351890/48297258-14225880-e472-11e8-8bd6-4203fc4cf6e1.png)
